---
AWSTemplateFormatVersion: "2010-09-09"

Description:
  This CloudFormation script acts as the root template and will create the
  infrastructure for the coding challenge

Parameters:
  VpcCidrParam:
    Type: String
    Description: Enter the CIDR of the VPC
  PrivateSubnetAParam:
    Type: String
    Description: Enter the CIDR of private subnet A
  PrivateSubnetBParam:
    Type: String
    Description: Enter the CIDR of private subnet B
  PublicSubnetAParam:
    Type: String
    Description: Enter the CIDR of public subnet A
  PublicSubnetBParam:
    Type: String
    Description: Enter the CIDR of public subnet B
  RegionParam:
    Type: String
    Description: Enter the name of the region
    AllowedValues:
      - Singapore
  S3BucketParam:
    Type: String
    Description: Bucket name where templates are stored
  SSHKeyNameParam:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Amazon EC2 Key Pair

Resources:
  VpcStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL:
        Fn::Join:
        - '/'
        - - !Sub "https://${S3BucketParam}.s3.amazonaws.com"
          - vpc.template.yaml
      Parameters:
        VpcCidrParam: !Ref VpcCidrParam
        PrivateSubnetAParam: !Ref PrivateSubnetAParam
        PrivateSubnetBParam: !Ref PrivateSubnetBParam
        PublicSubnetAParam: !Ref PublicSubnetAParam
        PublicSubnetBParam: !Ref PublicSubnetBParam
        RegionParam: !Ref RegionParam

  WebTierStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL:
        - '/'
        - - !Sub "https://${S3BucketParam}.s3.amazonaws.com"
          - web.template.yaml
      Parameters:
        SSHKeyNameParam: !Ref SSHKeyNameParam
        VpcIdParam: !GetAtt VpcStack.Outputs.VpcId
        PublicSubnetsParam:
          Fn::Join:
          - ', '
          - - !GetAtt VpcStack.Outputs.PublicSubnetA
          - - !GetAtt VpcStack.Outputs.PublicSubnetB
        PrivateSubnetsParam:
          Fn::Join:
          - ', '
          - - !GetAtt VpcStack.Outputs.PrivateSubnetA
          - - !GetAtt VpcStack.Outputs.PrivateSubnetB
        InitialWebServerCapacityParam: 2
